### ISSUE TITLE
Game Templates no longer available

### ISSUE THREAD

**Issue by pyRobShrk** [yutao-huang/office-scripts-conway-game-of-life#2]
I get this error:
Line 274: NetworkError when attempting to fetch resource.

When the script was trying to access:
https://rule-fetch.glitch.me/glider.rle

Can the rules be hosted in this repository?

**Comment by yutao-huang** [comment]
@pyRobShrk - Thanks for pointing out the issue and sorry for the late response.

Unfortunately, I don't think I can host the pattern rule files (originally hosted on <https://copy.sh/life/examples/>) on my repo since I don't own them. And neither can I directly download them from <https://copy.sh/life/examples/> from inside the Office Scripts code, because of [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) restrictions of that website.

I had to use a kind of "CORS proxy" service as a workaround. But the previously used proxy service was down for some reason.

I just set up a new CORS proxy for myself and it should be working now!
